// Code generated by goctl. DO NOT EDIT.
package types

type ApiTargetAppListReq struct {
	Page int32 `json:"page" validate:"required"`
	Size int32 `json:"size" validate:"required"`
}

type ApiTargetAppListResp struct {
	AppList []ApiTargetApp `json:"appList"`
}

type ApiTargetApp struct {
	AppCode           string  `json:"appCode"`
	AppName           string  `json:"appName"`
	AppIcon           string  `json:"appIcon"`
	Watermark         *string `json:"watermark,optional"`
	WatermarkPosition *int32  `json:"watermarkPosition,optional"`
}

type TestGetPathReq struct {
	Id string `path:"id"`
}

type TestGetQueryReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type TestGetJsonReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type TestPostFormReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type TestPostJsonReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type CustomerUpdateStateReq struct {
	AppCode string `json:"appCode" validate:"required"`
	State   int32  `json:"state" validate:"gte=0,lte=1"`
}

type CreateApplicationReq struct {
	AppName string `json:"appName" validate:"required"`
	AppDesc string `json:"appDesc"`
}

type OpenApplicationReq struct {
	ApplicationId int64  `json:"applicationId" validate:"required"`
	Option        int32  `json:"option" validate:"required,gte=1,lte=3"`
	AppAbilityUrl string `json:"appAbilityUrl,optional"`
}

type UpdateApplicationInfoReq struct {
	AppId         int64  `json:"appId" validate:"required"`
	AppName       string `json:"appName" validate:"required"`
	AppIconFileId string `json:"appIconFileId" validate:"required"`
	AppDesc       string `json:"appDesc" validate:"required"`
}
