// Code generated by goctl. DO NOT EDIT!
// Source: application.proto

package server

import (
	"context"

	"qbq-open-platform/applicationCenter/rpc/internal/logic/applicationapi"
	"qbq-open-platform/applicationCenter/rpc/internal/svc"
	"qbq-open-platform/applicationCenter/rpc/pb"
)

type ApplicationApiServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedApplicationApiServer
}

func NewApplicationApiServer(svcCtx *svc.ServiceContext) *ApplicationApiServer {
	return &ApplicationApiServer{
		svcCtx: svcCtx,
	}
}

//  查询可投递的应用列表
func (s *ApplicationApiServer) ApiTargetAppList(ctx context.Context, in *pb.ApiTargetAppListReq) (*pb.ApiTargetAppListResp, error) {
	l := applicationapilogic.NewApiTargetAppListLogic(ctx, s.svcCtx)
	return l.ApiTargetAppList(in)
}
