// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: pb/application.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiTargetAppListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ApiTargetAppListReq) Reset() {
	*x = ApiTargetAppListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiTargetAppListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiTargetAppListReq) ProtoMessage() {}

func (x *ApiTargetAppListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiTargetAppListReq.ProtoReflect.Descriptor instead.
func (*ApiTargetAppListReq) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{0}
}

func (x *ApiTargetAppListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ApiTargetAppListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ApiTargetAppListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppList []*ApiTargetApp `protobuf:"bytes,1,rep,name=appList,proto3" json:"appList,omitempty"`
}

func (x *ApiTargetAppListResp) Reset() {
	*x = ApiTargetAppListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiTargetAppListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiTargetAppListResp) ProtoMessage() {}

func (x *ApiTargetAppListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiTargetAppListResp.ProtoReflect.Descriptor instead.
func (*ApiTargetAppListResp) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{1}
}

func (x *ApiTargetAppListResp) GetAppList() []*ApiTargetApp {
	if x != nil {
		return x.AppList
	}
	return nil
}

type ApiTargetApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppCode           string `protobuf:"bytes,1,opt,name=appCode,proto3" json:"appCode,omitempty"`
	AppName           string `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	AppIcon           string `protobuf:"bytes,3,opt,name=appIcon,proto3" json:"appIcon,omitempty"`
	Watermark         string `protobuf:"bytes,4,opt,name=watermark,proto3" json:"watermark,omitempty"`
	WatermarkPosition int32  `protobuf:"varint,5,opt,name=watermarkPosition,proto3" json:"watermarkPosition,omitempty"`
}

func (x *ApiTargetApp) Reset() {
	*x = ApiTargetApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiTargetApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiTargetApp) ProtoMessage() {}

func (x *ApiTargetApp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiTargetApp.ProtoReflect.Descriptor instead.
func (*ApiTargetApp) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{2}
}

func (x *ApiTargetApp) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *ApiTargetApp) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ApiTargetApp) GetAppIcon() string {
	if x != nil {
		return x.AppIcon
	}
	return ""
}

func (x *ApiTargetApp) GetWatermark() string {
	if x != nil {
		return x.Watermark
	}
	return ""
}

func (x *ApiTargetApp) GetWatermarkPosition() int32 {
	if x != nil {
		return x.WatermarkPosition
	}
	return 0
}

type CustomerUpdateStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppCode string `protobuf:"bytes,1,opt,name=appCode,proto3" json:"appCode,omitempty"`
	State   int32  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *CustomerUpdateStateReq) Reset() {
	*x = CustomerUpdateStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerUpdateStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerUpdateStateReq) ProtoMessage() {}

func (x *CustomerUpdateStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerUpdateStateReq.ProtoReflect.Descriptor instead.
func (*CustomerUpdateStateReq) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerUpdateStateReq) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *CustomerUpdateStateReq) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type CustomerUpdateStateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomerUpdateStateResp) Reset() {
	*x = CustomerUpdateStateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerUpdateStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerUpdateStateResp) ProtoMessage() {}

func (x *CustomerUpdateStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerUpdateStateResp.ProtoReflect.Descriptor instead.
func (*CustomerUpdateStateResp) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{4}
}

type CreateApplicationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName        string `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	AppDesc        string `protobuf:"bytes,2,opt,name=appDesc,proto3" json:"appDesc,omitempty"`
	AppDeveloperId int64  `protobuf:"varint,3,opt,name=appDeveloperId,proto3" json:"appDeveloperId,omitempty"`
}

func (x *CreateApplicationReq) Reset() {
	*x = CreateApplicationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationReq) ProtoMessage() {}

func (x *CreateApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationReq.ProtoReflect.Descriptor instead.
func (*CreateApplicationReq) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{5}
}

func (x *CreateApplicationReq) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateApplicationReq) GetAppDesc() string {
	if x != nil {
		return x.AppDesc
	}
	return ""
}

func (x *CreateApplicationReq) GetAppDeveloperId() int64 {
	if x != nil {
		return x.AppDeveloperId
	}
	return 0
}

type CreateApplicationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateApplicationResp) Reset() {
	*x = CreateApplicationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationResp) ProtoMessage() {}

func (x *CreateApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationResp.ProtoReflect.Descriptor instead.
func (*CreateApplicationResp) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{6}
}

type OpenApplicationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationId int64  `protobuf:"varint,1,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	Option        int32  `protobuf:"varint,2,opt,name=option,proto3" json:"option,omitempty"`
	AbilityUrl    string `protobuf:"bytes,3,opt,name=abilityUrl,proto3" json:"abilityUrl,omitempty"`
}

func (x *OpenApplicationReq) Reset() {
	*x = OpenApplicationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenApplicationReq) ProtoMessage() {}

func (x *OpenApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenApplicationReq.ProtoReflect.Descriptor instead.
func (*OpenApplicationReq) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{7}
}

func (x *OpenApplicationReq) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *OpenApplicationReq) GetOption() int32 {
	if x != nil {
		return x.Option
	}
	return 0
}

func (x *OpenApplicationReq) GetAbilityUrl() string {
	if x != nil {
		return x.AbilityUrl
	}
	return ""
}

type OpenApplicationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpenApplicationResp) Reset() {
	*x = OpenApplicationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenApplicationResp) ProtoMessage() {}

func (x *OpenApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenApplicationResp.ProtoReflect.Descriptor instead.
func (*OpenApplicationResp) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{8}
}

type UpdateApplicationInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId         int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppName       string `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	AppIconFileId string `protobuf:"bytes,3,opt,name=appIconFileId,proto3" json:"appIconFileId,omitempty"`
	AppDesc       string `protobuf:"bytes,4,opt,name=appDesc,proto3" json:"appDesc,omitempty"`
}

func (x *UpdateApplicationInfoReq) Reset() {
	*x = UpdateApplicationInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateApplicationInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationInfoReq) ProtoMessage() {}

func (x *UpdateApplicationInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateApplicationInfoReq) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateApplicationInfoReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *UpdateApplicationInfoReq) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *UpdateApplicationInfoReq) GetAppIconFileId() string {
	if x != nil {
		return x.AppIconFileId
	}
	return ""
}

func (x *UpdateApplicationInfoReq) GetAppDesc() string {
	if x != nil {
		return x.AppDesc
	}
	return ""
}

type UpdateApplicationInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateApplicationInfoResp) Reset() {
	*x = UpdateApplicationInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateApplicationInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationInfoResp) ProtoMessage() {}

func (x *UpdateApplicationInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationInfoResp.ProtoReflect.Descriptor instead.
func (*UpdateApplicationInfoResp) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{10}
}

type CreateApplicationCallbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppCode     string `protobuf:"bytes,1,opt,name=AppCode,proto3" json:"AppCode,omitempty"`
	AppName     string `protobuf:"bytes,2,opt,name=AppName,proto3" json:"AppName,omitempty"`
	CallbackUrl string `protobuf:"bytes,3,opt,name=CallbackUrl,proto3" json:"CallbackUrl,omitempty"`
	RetryConfig string `protobuf:"bytes,4,opt,name=RetryConfig,proto3" json:"RetryConfig,omitempty"`
}

func (x *CreateApplicationCallbackReq) Reset() {
	*x = CreateApplicationCallbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateApplicationCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationCallbackReq) ProtoMessage() {}

func (x *CreateApplicationCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationCallbackReq.ProtoReflect.Descriptor instead.
func (*CreateApplicationCallbackReq) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{11}
}

func (x *CreateApplicationCallbackReq) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *CreateApplicationCallbackReq) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateApplicationCallbackReq) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *CreateApplicationCallbackReq) GetRetryConfig() string {
	if x != nil {
		return x.RetryConfig
	}
	return ""
}

type CreateApplicationCallbackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateApplicationCallbackResp) Reset() {
	*x = CreateApplicationCallbackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateApplicationCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationCallbackResp) ProtoMessage() {}

func (x *CreateApplicationCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationCallbackResp.ProtoReflect.Descriptor instead.
func (*CreateApplicationCallbackResp) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{12}
}

type UpdateApplicationCallbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppCode     string `protobuf:"bytes,1,opt,name=AppCode,proto3" json:"AppCode,omitempty"`
	AppName     string `protobuf:"bytes,2,opt,name=AppName,proto3" json:"AppName,omitempty"`
	CallbackUrl string `protobuf:"bytes,3,opt,name=CallbackUrl,proto3" json:"CallbackUrl,omitempty"`
	RetryConfig string `protobuf:"bytes,4,opt,name=RetryConfig,proto3" json:"RetryConfig,omitempty"`
}

func (x *UpdateApplicationCallbackReq) Reset() {
	*x = UpdateApplicationCallbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateApplicationCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationCallbackReq) ProtoMessage() {}

func (x *UpdateApplicationCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationCallbackReq.ProtoReflect.Descriptor instead.
func (*UpdateApplicationCallbackReq) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateApplicationCallbackReq) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *UpdateApplicationCallbackReq) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *UpdateApplicationCallbackReq) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *UpdateApplicationCallbackReq) GetRetryConfig() string {
	if x != nil {
		return x.RetryConfig
	}
	return ""
}

type UpdateApplicationCallbackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateApplicationCallbackResp) Reset() {
	*x = UpdateApplicationCallbackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateApplicationCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationCallbackResp) ProtoMessage() {}

func (x *UpdateApplicationCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationCallbackResp.ProtoReflect.Descriptor instead.
func (*UpdateApplicationCallbackResp) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{14}
}

type GetApplicationCallbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppCode string `protobuf:"bytes,1,opt,name=AppCode,proto3" json:"AppCode,omitempty"`
}

func (x *GetApplicationCallbackReq) Reset() {
	*x = GetApplicationCallbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicationCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationCallbackReq) ProtoMessage() {}

func (x *GetApplicationCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationCallbackReq.ProtoReflect.Descriptor instead.
func (*GetApplicationCallbackReq) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{15}
}

func (x *GetApplicationCallbackReq) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

type GetApplicationCallbackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppCode     string `protobuf:"bytes,1,opt,name=AppCode,proto3" json:"AppCode,omitempty"`
	AppName     string `protobuf:"bytes,2,opt,name=AppName,proto3" json:"AppName,omitempty"`
	CallbackUrl string `protobuf:"bytes,3,opt,name=CallbackUrl,proto3" json:"CallbackUrl,omitempty"`
	RetryConfig string `protobuf:"bytes,4,opt,name=RetryConfig,proto3" json:"RetryConfig,omitempty"`
}

func (x *GetApplicationCallbackResp) Reset() {
	*x = GetApplicationCallbackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicationCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationCallbackResp) ProtoMessage() {}

func (x *GetApplicationCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationCallbackResp.ProtoReflect.Descriptor instead.
func (*GetApplicationCallbackResp) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{16}
}

func (x *GetApplicationCallbackResp) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *GetApplicationCallbackResp) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *GetApplicationCallbackResp) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *GetApplicationCallbackResp) GetRetryConfig() string {
	if x != nil {
		return x.RetryConfig
	}
	return ""
}

type CreateApplicationCallbackOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   string `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	AppCode     string `protobuf:"bytes,2,opt,name=AppCode,proto3" json:"AppCode,omitempty"`
	AppName     string `protobuf:"bytes,3,opt,name=AppName,proto3" json:"AppName,omitempty"`
	CallbackUrl string `protobuf:"bytes,4,opt,name=CallbackUrl,proto3" json:"CallbackUrl,omitempty"`
	RetryConfig string `protobuf:"bytes,5,opt,name=RetryConfig,proto3" json:"RetryConfig,omitempty"`
	Status      int32  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Param       string `protobuf:"bytes,7,opt,name=Param,proto3" json:"Param,omitempty"`
	TaskCode    string `protobuf:"bytes,8,opt,name=TaskCode,proto3" json:"TaskCode,omitempty"`
	Message     string `protobuf:"bytes,9,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *CreateApplicationCallbackOrderReq) Reset() {
	*x = CreateApplicationCallbackOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_application_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateApplicationCallbackOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationCallbackOrderReq) ProtoMessage() {}

func (x *CreateApplicationCallbackOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_application_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationCallbackOrderReq.ProtoReflect.Descriptor instead.
func (*CreateApplicationCallbackOrderReq) Descriptor() ([]byte, []int) {
	return file_pb_application_proto_rawDescGZIP(), []int{17}
}

func (x *CreateApplicationCallbackOrderReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateApplicationCallbackOrderReq) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *CreateApplicationCallbackOrderReq) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateApplicationCallbackOrderReq) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *CreateApplicationCallbackOrderReq) GetRetryConfig() string {
	if x != nil {
		return x.RetryConfig
	}
	return ""
}

func (x *CreateApplicationCallbackOrderReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateApplicationCallbackOrderReq) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *CreateApplicationCallbackOrderReq) GetTaskCode() string {
	if x != nil {
		return x.TaskCode
	}
	return ""
}

func (x *CreateApplicationCallbackOrderReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_application_proto protoreflect.FileDescriptor

var file_pb_application_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3d, 0x0a, 0x13, 0x41, 0x70,
	0x69, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x42, 0x0a, 0x14, 0x41, 0x70, 0x69,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2a, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x69, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x41, 0x70, 0x70, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xa8, 0x01,
	0x0a, 0x0c, 0x41, 0x70, 0x69, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x70, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x2c, 0x0a, 0x11, 0x77, 0x61,
	0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x16, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x72, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x44, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x44, 0x65, 0x73, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70, 0x70,
	0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x61, 0x70, 0x70, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x72, 0x0a, 0x12, 0x4f, 0x70,
	0x65, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x24, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x55, 0x72, 0x6c, 0x22, 0x15,
	0x0a, 0x13, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x8a, 0x01, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x49, 0x63, 0x6f, 0x6e, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x49, 0x63,
	0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x44,
	0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x44, 0x65,
	0x73, 0x63, 0x22, 0x1b, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x96, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x74, 0x72, 0x79, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x96, 0x01, 0x0a, 0x1c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c,
	0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x22, 0x1f, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x35, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x70, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x12,
	0x20, 0x0a, 0x0b, 0x52, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x22, 0x9d, 0x02, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x52, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x54,
	0x61, 0x73, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54,
	0x61, 0x73, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x57, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x70, 0x69, 0x12, 0x45, 0x0a, 0x10, 0x41, 0x70, 0x69, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x69,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x69, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41,
	0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x32, 0xc9, 0x02, 0x0a, 0x13, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x12, 0x4e, 0x0a, 0x13, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x48, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0f,
	0x4f, 0x70, 0x65, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x54, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_application_proto_rawDescOnce sync.Once
	file_pb_application_proto_rawDescData = file_pb_application_proto_rawDesc
)

func file_pb_application_proto_rawDescGZIP() []byte {
	file_pb_application_proto_rawDescOnce.Do(func() {
		file_pb_application_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_application_proto_rawDescData)
	})
	return file_pb_application_proto_rawDescData
}

var file_pb_application_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pb_application_proto_goTypes = []interface{}{
	(*ApiTargetAppListReq)(nil),               // 0: pb.ApiTargetAppListReq
	(*ApiTargetAppListResp)(nil),              // 1: pb.ApiTargetAppListResp
	(*ApiTargetApp)(nil),                      // 2: pb.ApiTargetApp
	(*CustomerUpdateStateReq)(nil),            // 3: pb.CustomerUpdateStateReq
	(*CustomerUpdateStateResp)(nil),           // 4: pb.CustomerUpdateStateResp
	(*CreateApplicationReq)(nil),              // 5: pb.CreateApplicationReq
	(*CreateApplicationResp)(nil),             // 6: pb.CreateApplicationResp
	(*OpenApplicationReq)(nil),                // 7: pb.OpenApplicationReq
	(*OpenApplicationResp)(nil),               // 8: pb.OpenApplicationResp
	(*UpdateApplicationInfoReq)(nil),          // 9: pb.UpdateApplicationInfoReq
	(*UpdateApplicationInfoResp)(nil),         // 10: pb.UpdateApplicationInfoResp
	(*CreateApplicationCallbackReq)(nil),      // 11: pb.CreateApplicationCallbackReq
	(*CreateApplicationCallbackResp)(nil),     // 12: pb.CreateApplicationCallbackResp
	(*UpdateApplicationCallbackReq)(nil),      // 13: pb.UpdateApplicationCallbackReq
	(*UpdateApplicationCallbackResp)(nil),     // 14: pb.UpdateApplicationCallbackResp
	(*GetApplicationCallbackReq)(nil),         // 15: pb.GetApplicationCallbackReq
	(*GetApplicationCallbackResp)(nil),        // 16: pb.GetApplicationCallbackResp
	(*CreateApplicationCallbackOrderReq)(nil), // 17: pb.CreateApplicationCallbackOrderReq
}
var file_pb_application_proto_depIdxs = []int32{
	2,  // 0: pb.ApiTargetAppListResp.appList:type_name -> pb.ApiTargetApp
	0,  // 1: pb.ApplicationApi.ApiTargetAppList:input_type -> pb.ApiTargetAppListReq
	3,  // 2: pb.ApplicationCustomer.CustomerUpdateState:input_type -> pb.CustomerUpdateStateReq
	5,  // 3: pb.ApplicationCustomer.CreateApplication:input_type -> pb.CreateApplicationReq
	7,  // 4: pb.ApplicationCustomer.OpenApplication:input_type -> pb.OpenApplicationReq
	9,  // 5: pb.ApplicationCustomer.UpdateApplicationInfo:input_type -> pb.UpdateApplicationInfoReq
	1,  // 6: pb.ApplicationApi.ApiTargetAppList:output_type -> pb.ApiTargetAppListResp
	4,  // 7: pb.ApplicationCustomer.CustomerUpdateState:output_type -> pb.CustomerUpdateStateResp
	6,  // 8: pb.ApplicationCustomer.CreateApplication:output_type -> pb.CreateApplicationResp
	8,  // 9: pb.ApplicationCustomer.OpenApplication:output_type -> pb.OpenApplicationResp
	10, // 10: pb.ApplicationCustomer.UpdateApplicationInfo:output_type -> pb.UpdateApplicationInfoResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pb_application_proto_init() }
func file_pb_application_proto_init() {
	if File_pb_application_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_application_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiTargetAppListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiTargetAppListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiTargetApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerUpdateStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerUpdateStateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateApplicationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateApplicationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenApplicationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenApplicationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateApplicationInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateApplicationInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateApplicationCallbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateApplicationCallbackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateApplicationCallbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateApplicationCallbackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicationCallbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicationCallbackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_application_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateApplicationCallbackOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_application_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_application_proto_goTypes,
		DependencyIndexes: file_pb_application_proto_depIdxs,
		MessageInfos:      file_pb_application_proto_msgTypes,
	}.Build()
	File_pb_application_proto = out.File
	file_pb_application_proto_rawDesc = nil
	file_pb_application_proto_goTypes = nil
	file_pb_application_proto_depIdxs = nil
}
